### ISSUE TITLE
"roughly 21 million bitcoins" 

### ISSUE THREAD

**Issue by raindogdance** [paralelolab/bitcoindesigned-infographics-i18n#1]
as seen in: 

https://github.com/lxparallel/bitcoindesigned-infographics-i18n/blob/cc0761ae261beacb4bce1346b625734da8f62582/what-is-bitcoin-the-currency/source-text.txt#L17 

I would rather say "exactly", instead of "roughly", since the 21 million is pretty much a fixed amount of issuance? The amount of circulation is of course different, but the issuance number won't go anywhere :)

**Comment by raindogdance** [comment]
another small typo: https://github.com/lxparallel/bitcoindesigned-infographics-i18n/blob/cc0761ae261beacb4bce1346b625734da8f62582/what-is-bitcoin-the-currency/source-text.txt#L41 (`ou` instead of `or`)

**Comment by UnholyLizard** [comment]
> I would rather say "exactly", instead of "roughly", since the 21 million is pretty much a fixed amount of issuance?

Well, last 'full' bitcoin will never ever be mined. 

From: [bitcoinwiki](https://en.bitcoin.it/wiki/Help:FAQ#How_long_will_it_take_to_generate_all_the_coins.3F)

> The total number of coins in circulation will then remain static at 20,999,999.9769 BTC. Even if the allowed precision is expanded from the current 8 decimals, **_the total BTC in circulation will always be slightly below 21 million_** (assuming everything else stays the same). For example, with 16 decimals of precision, the end total would be 20,999,999.999999999496 BTC.

So "**exactly**" isn't true either..

**Comment by patestevao** [comment]
Hi, @raindogdance. Thanks for helping. 
I had the same idea of @UnholyLizard about this number, but, just to make things more clear, I changed the phrasing from "roughly 21 million to be ever issued" to "roughly 21 million to be ever put in circulation".
Also, there was definitely a typo where you pointed out, so I've corrected it as well.
Thank you!
