### ISSUE TITLE
Typo 'stablished' -> 'established'

### ISSUE THREAD

**Issue by UnholyLizard** [paralelolab/bitcoindesigned-infographics-i18n#5]
https://github.com/lxparallel/bitcoindesigned-infographics-i18n/blob/cc0761ae261beacb4bce1346b625734da8f62582/understanding-the-lightning-network-part-2/source-text.txt#L11

'stablished' -> 'established' ?

**Comment by patestevao** [comment]
Just fixed it, thank you!
