### ISSUE TITLE
Typo in description M of N scheme?

### ISSUE THREAD

**Issue by UnholyLizard** [paralelolab/bitcoindesigned-infographics-i18n#8]
https://github.com/lxparallel/bitcoindesigned-infographics-i18n/blob/152ac1fd549cd563728ffabe288bfff814a59bf3/what-is-a-multisig-wallet/source-text.txt#L15-L25

'M of N' and not 'N of M' so looks like we need change N and M.

>  The m-of-n scheme means that the wallet is associated with **n** keys and each time a transaction needs to be broadcast, **m** of those m keys need to sign it. 
>   
>  **n** keys 
>   
>  **n** = 4 
>   
>  **m** signatures 
>   
>  **m** = 3

**Comment by patestevao** [comment]
You're absolutely correct. I've just fixed it. 
Thank you!!
